title: PASHA Management Consultancy
description: Pasha Management Consultancy Ltd. (“PMC”) is a boutique accounting, advisory & consulting firm, headquartered in Ontario, Canada, that provides a wide array of Accounting & Advisory services to clients throughout the North America and Saudi Arabia region.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

